import "../../styles/globals.css"
import { Inter } from 'next/font/google'
import Header from "../components/Header"
import Banner from "../components/Banner"
import Footer from "../components/footer"



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
}

export default function BlogsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col justify-between">
        <header className="mx-[150px]">
            <Header />
        </header>

        <main className="mx-[262px]">
          <Banner heading='All Posts' />
          <hr className="border-[#F7AB0A] my-14 bg-white h-0"/>
          {children}
          <hr className="border-[#F7AB0A] my-14 bg-white h-0"/>
        </main>

        <footer>
          <Footer />
        </footer>

      </body>
    </html>
  )
}