export const metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
}

export default function BlogsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className="min-h-screen flex flex-col justify-between">
          {children}
      </div>
  )
}