import "../../styles/globals.css"
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Footer from '../components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col justify-between">
      <header className='lg:mx-[150px] md:mx-[100px]'>
      <Header />
      </header>

      <main className="mx-[162px]">
        {children}
      </main>

      <footer className='mt-20'>
        <Footer />
      </footer>

      </body>
    </html>
  )
}