import { Inter } from "next/font/google";
import Header from "../../components/Header";
import "../../../styles/globals.css";
import { authOptions, getAuthSession } from "@/lib/authOptions";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SUYASH'S BLOG | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getAuthSession()

  if(!session?.user) redirect("/sign-in")
  return (
        <div>
          {children}
        </div>
  );
}
