import Header from "@/app/components/Header"
import "../../../styles/globals.css"
import { Inter } from 'next/font/google'
import Footer from "@/app/components/footer"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header className='lg:mx-[162px]'>
      <Header />
        {children}
      </header>
        <footer className='mt-20'>
          <Footer />
        </footer>
      </body>
    </html>
  )
}