import { getAuthSession } from "@/lib/authOptions"
import { redirect } from "next/navigation"
import "../../styles/globals.css"

export const metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
}

export default async function BlogsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const session = await getAuthSession()

  return (
      <div>
          {children}
      </div>
  )
}