import "../../styles/globals.css"
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import HomePageFooter from "../components/HomePageFooter"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "SUYASH'S BLOG | Home",
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="lg:mx-[150px] md:mx-[100px]">
      <header>
      <Header />
      </header>

        {children}
      
        </div>
      <footer>
        <HomePageFooter />
      </footer>
      </body>
    </html>
  )
}
