import "../../styles/globals.css"
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Footer from '../components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "SUYASH'S BLOG | Home",
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen lg:mx-[150px] md:mx-[100px]">
      <header>
      <Header />
      </header>

        {children}
      
      <footer className='mt-20'>
        <Footer />
      </footer>
      </body>
    </html>
  )
}
